### ISSUE TITLE
Add new paper pls

### ISSUE THREAD

**Issue by Lin-Yijie** [Paranioar/Cross-modal_Retrieval_Tutorial#5]
Hi Paranioar! Could you please include this recent work about video-language pretraining and noisy correspondence? Thanks a lot.

**(ICLR2024_Norton) Multi-granularity Correspondence Learning from Long-term Noisy Videos**  
*Yijie Lin, Jie Zhang, Zhenyu Huang, Jia Liu, Zujie Wen, Xi Peng*.
[[paper]](https://lin-yijie.github.io/projects/Norton/) [[code]](https://github.com/XLearning-SCU/2024-ICLR-Norton)

**Comment by Paranioar** [comment]
> Hi Paranioar! Could you please include this recent work about video-language pretraining and noisy correspondence? Thanks a lot.
> 
> **(ICLR2024_Norton) Multi-granularity Correspondence Learning from Long-term Noisy Videos** _Yijie Lin, Jie Zhang, Zhenyu Huang, Jia Liu, Zujie Wen, Xi Peng_. [[paper]](https://lin-yijie.github.io/projects/Norton/) [[code]](https://github.com/XLearning-SCU/2024-ICLR-Norton)

Great work! I will update this project next week.
We really welcome the latest papers to polish this project.
